name = input ("Hi there, Whats your name?")
print (f"well hi there {name}")
answer = input (f"Do you want to hear a couple of jokes,{name}?If you do, type 'YES'. If you are not interested, type 'NO'.")
if answer == 'NO':
    print("to bad, press enter!!")
elif answer == 'YES':
    print ("Ok, thanks!")
    print ("What do you call fake spagaetti??")
input ()
input ("Do you think you know it?")
input ("I bet you don't!")
input ("Wait for it once more...")
input ()
print ("impasta")
input ()
print ("Do you want to hear another joke?")
print ("Press enter if you want to hear it")
input ("Error") 
input ()
input ("Error")
input ("PRESS ENTER")
print ("ERROR")
input (f"{name},go ask your teacher what is wrong with your computer")
input ("hahha just kidding! That was the joke! You got fooled")
print(f"Thank you,{name}")
