print ("YOU ARE NOW TALKING TO CHAD THE CHAT ")
print ("")
print ("Hi!! My name is Chad")
name = input ("What is your name:")
input (f"Well hi there {name}! Nice to meet you!")
answer = input (f"Would you like to have a conversation, {name}? Type 'YES' if you would like to and 'NO' if not:")
if answer == 'YES':
    print ("Ok, YAY! Thanks!")
    print ("Lets talk about...")
    print ("How about, sports?")
elif answer == 'NO':
    print ("Well, your lose")
    print ("Come back if you ever need to talk!")
    print ("Goodbye")
    print ("")
    print ("")
    input ("")
    input ("")
    input ("")
    input ("")
    input ("")
    input ("")
    input ("")
    input ("")
sports = input ("What is your favorite sport to play?")
print (f"Woah! No way, I like {sports} too! We should play {sports} sometime together!")
print ("") 
player = input (f"Whats your favorite professional player in {sports}?")
print (f"oh, you like {player}. Ew. I mean, I respect your opinion.")
input ()
day = input("Omg! I am so rude! I forgot to ask you how your day is going! Well, better late then never. Hows your day going?:")
input (f"Oh, I hear you. My day is {day} too but its gotten even better from talking to you!")
print ()
input ("Well...")
answer = input ("Should we continue this conversation? Please answer 'yes' or 'no':")
if answer == 'no':
    print ()
    print ("Well ok, I had a fun time talking with you!")
    print ("Come again anytime when you need a pal by your side")
    print ("haha well...")
    print ("SO LONG")
    print ("-CHAD THE CHAT")
    input ("")
    input ("")
    input ("")
    input ("")
    input ("")
    input ("")
    input ("")
    input ("")
if answer == 'yes':
    print ("Ok! You read my mind!")
    print ("Hmm... Now lets talk about...")
    input ("Ooooh, I have an idea...")
    input ("Lets talk about school!")
school = input ("Whats your favorite class:")
input (f"oh really! You like {school}??? Wow! Thats VERY interesting. I like Math.")
input ("Well, I had a great time talking to you and please come again whenever you need a friend!")
print ("Signing off")
print ("-Chad the Chat")